# layout = {
#   border = {
#     width = "2";
#     radius = {
#       size = "10";
#       inner = "7";
#     };
#   };
#   font = {
#     name = "MapleMono Nerd Font Propo";
#     mono = "MapleMono Nerd Font Mono";
#     sub = "10";
#     size = "12";
#     title = "18";
#   };
#   background = {
#     opacity = 0.4;
#     opacity_hex = "66";
#   };
#   gap = {
#     size = "20";
#     inner = "10";
#   };
#   # css: filter: blur(calc(size * sqrt(passes) * 0.85px));
#   blur = {
#     size = "5";
#     passes = "4";
#   };
# };
{
  lib,
  pkgs,
  config,
  inputs,
  wrappers,
  ...
}: {
  environment.sessionVariables = {
    EDITOR = "nvim";
    NIXOS_OZONE_WL = 1;
    QT_QPA_PLATFORM = "wayland";

    # googledot-black pkgs.google-cursor
    XCURSOR_THEME = "phinger-cursors-dark";
    XCURSOR_SIZE = 24;
  };

  networking.hostName = config.preferences.hostname;
  nix.settings.experimental-features = ["nix-command" "flakes"];

  users.users.${config.preferences.username} = {
    isNormalUser = true;
    extraGroups = ["wheel" "input"];
    initialPassword = config.preferences.username;
  };

  qt.enable = true;
  programs.nix-ld.enable = true;

  programs.hyprland = {
    enable = true;
    withUWSM = true;
    package = let
      configFile = ../../dotfiles/hyprland.lua;
      pluginLoading = let
        plugins = [
          inputs.hypr-dynamic-cursors.packages.${pkgs.stdenv.hostPlatform.system}.hypr-dynamic-cursors
          pkgs.hyprlandPlugins.hyprcapture
        ];
        getPath = plugin:
          if lib.types.package.check plugin
          then "${plugin}/lib/lib${plugin.pname}.so"
          else plugin;
      in ''
        -- GENERATED BY NIX-WRAPPER-MODULES
        hl.on("hyprland.start", function()
        ${lib.concatMapStringsSep "\n" (
            plugin: "  hl.exec_cmd(\"hyprctl plugin load ${getPath plugin}\")"
          )
          plugins}
        end)
        -- END GENERATED
      '';
    in
      wrappers.lib.evalPackage [
        {inherit pkgs;}
        ({
          pkgs,
          wlib,
          config,
          ...
        }: {
          imports = [wlib.modules.default];
          package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
          flags."--config" = pkgs.writeText "hyprland.lua" ''
            ${pluginLoading}
            ${builtins.readFile configFile}
          '';

          inherit (config.package) passthru;
        })
      ];
    portalPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland;
  };
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      rocmPackages.clr.icd
    ];
  };
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    audio.enable = true;
    wireplumber.enable = true;

    alsa = {
      enable = true;
      support32Bit = true;
    };
    jack.enable = true;
    pulse.enable = true;
  };

  boot-loader = {
    systemd-boot.enable = true;
    timeout = 10;
    extraConfig = ''
      auto-entries no
    '';
    extraEntries = [
      {
        name = "windows11";
        title = "Windows 11";
        efi = "/EFI/Microsoft/boot/bootmgfw.efi";
        sortKey = "a_windows";
      }
    ];
  };
  boot.kernelPackages = pkgs.linuxPackages_latest;

  services.greetd = {
    enable = true;
    settings = rec {
      initial_session = {
        user = config.preferences.username;
        command = "${lib.getExe pkgs.uwsm} start hyprland.desktop";
      };
      default_session = initial_session;
    };
  };

  nixpkgs.config.allowUnfree = true;

  services.keyd = {
    enable = true;

    keyboards.default = {
      settings = {
        main = {
          shift = "oneshot(shift)";
          meta = "oneshot(meta)";
          control = "oneshot(control)";
          leftalt = "oneshot(alt)";
          rightalt = "oneshot(altgr)";

          capslock = "overload(control, esc)";
          esc = "capslock";
        };
      };
    };
  };

  # TEMPORARY --- will move to nixos-modules
  # networking.wireless.enable = true;
  # END TEMPORARY

  # TEMPORARY --- will move to nixos-modules
  time.timeZone = "Europe/Berlin";
  i18n.defaultLocale = "en_US.UTF-8";
  # END TEMPORARY

  # Fonts
  fonts.fontconfig.enable = true;
  fonts.packages = with pkgs; [
    (callPackage ../../packages/maple-nerd-font-mono.nix {})
    (callPackage ../../packages/maple-nerd-font-propo.nix {})

    material-symbols
  ];

  programs.git = {
    enable = true;
    package = wrappers.wrappers.git.wrap {
      inherit pkgs;
      settings = {
        user = {
          name = "jonas-elhs";
          email = "jonas.elhs@outlook.com";
        };
      };
    };
  };

  programs.fish = {
    enable = true;
    package = wrappers.wrappers.fish.wrap {
      inherit pkgs;

      plugins = with pkgs.fishPlugins; [
        autopair
      ];
      configFile.content = lib.concatStringsSep "\n" [
        ''
          fish_vi_key_bindings
          set -g fish_autosuggestion_enabled 0
          set -g fish_greeting
        ''
        (builtins.readFile ../../dotfiles/fish_prompt.fish)
      ];
    };
  };

  environment.systemPackages = with pkgs; [
    (inputs.wrappers-ghostty.wrappers.ghostty.wrap {
      inherit pkgs;

      settings = {
        theme = "system";
        font-size = 12;
        font-family = "MapleMono Nerd Font Mono";
        background-opacity = 0.4;

        window-padding-x = 8;
        window-padding-y = 8;
        window-padding-balance = true;

        adjust-cursor-thickness = "250%";
        adjust-underline-thickness = "25%";

        command = "fish";
        mouse-hide-while-typing = true;

        custom-shader = "~/.config/ghostty/shaders/cursor_warp.glsl";
      };
    })

    (wrappers.wrappers.jujutsu.wrap {
      inherit pkgs;

      settings = {
        user = {
          name = "jonas-elhs";
          email = "jonas.elhs@outlook.com";
        };
      };
    })

    (wrappers.wrappers.hypridle.wrap {
      inherit pkgs;

      settings = {
        general = {
          lock_cmd = "meshell lock";
          after_sleep_cmd = "hyprctl dispatch dpms on";
          before_sleep_cmd = "loginctl lock-session";
        };

        listener = [
          # Lock System - 5 Minutes
          {
            timeout = 300;
            on-timeout = "loginctl lock-session";
          }

          # Dim Screen - 20 Minutes
          {
            timeout = 1200;
            on-timeout = "hyprctl dispatch dpms off";
            on-resume = "hyprctl dispatch dpms on";
          }

          # Suspend System - 1 hour
          {
            timeout = 3600;
            on-timeout = "systemctl hibernate";
          }
        ];
      };
    })

    phinger-cursors
    runapp
    hyprpolkitagent
    hyprshutdown

    # krita
    hyprpicker
    fuzzel

    rustc
    cargo
    gcc
    gnumake
    cmake

    inputs.mevim.packages.x86_64-linux.default
    inputs.meshell.packages.x86_64-linux.cli
    inputs.meshell.packages.x86_64-linux.quickshell
    inputs.metemplate.packages.x86_64-linux.default

    nasm
    llvmPackages_latest.bintools-unwrapped
    lazygit
    uv
    teams-for-linux
    libnotify
    obs-studio
    davinci-resolve
    mpv
    pkg-config
    home-manager
    anki

    # TEMPORARY --- will move to home-manager
    wl-clipboard
    cursor-clip

    firefox

    tree
    # END TEMPORARY

    # MAIL
    thunderbird
    mailspring # wayland problem?
    bluemail
    # END MAIL

    # FILES
    #    xfce.thunar
    kdePackages.dolphin
    #    pcmanfm
    # END FILES
  ];

  system.stateVersion = "24.11";
}
