# TODO: create and upstream hyprland wrapper module
{
  lib,
  pkgs,
  inputs,
  wrappers,
  ...
}: {
  programs.hyprland = {
    enable = true;
    withUWSM = true;
    package = let
      configFile = ../../dotfiles/hyprland.lua;
      pluginLoading = let
        plugins = [
          inputs.hypr-dynamic-cursors.packages.${pkgs.stdenv.hostPlatform.system}.hypr-dynamic-cursors
          pkgs.hyprlandPlugins.hyprcapture
        ];
        getPath = plugin:
          if lib.types.package.check plugin
          then "${plugin}/lib/lib${plugin.pname}.so"
          else plugin;
      in ''
        -- GENERATED BY NIX-WRAPPER-MODULES
        hl.on("hyprland.start", function()
        ${lib.concatMapStringsSep "\n" (
            plugin: "  hl.exec_cmd(\"hyprctl plugin load ${getPath plugin}\")"
          )
          plugins}
        end)
        -- END GENERATED
      '';
    in
      wrappers.lib.evalPackage [
        {inherit pkgs;}
        ({
          pkgs,
          wlib,
          config,
          ...
        }: {
          imports = [wlib.modules.default];
          package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
          flags."--config" = pkgs.writeText "hyprland.lua" ''
            ${pluginLoading}
            ${builtins.readFile configFile}
          '';

          inherit (config.package) passthru;
        })
      ];
    portalPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland;
  };
}
